# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzQL2o49Vr0w8MRsgK-5Z6LFtSshZWOC
"""

# app.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import random

st.set_page_config(page_title="Generative Star Poster", layout="wide")

# --- Functions ---

def random_palette(k=6, mode="vivid"):
    cols = []
    for _ in range(k):
        if mode == "pastel":
            cols.append((random.uniform(0.6, 1.0), random.uniform(0.6, 1.0), random.uniform(0.6, 1.0)))
        elif mode == "vivid":
            cols.append((random.random(), random.random(), random.random()))
        else:
            cols.append(tuple(np.clip(np.random.rand(3), 0, 1)))
    return cols

def true_star(center=(0.5,0.5), r_outer=0.3, r_inner=0.15, num_points=5, wobble=0.1):
    cx, cy = center
    angles_outer = np.linspace(0, 2 * np.pi, num_points, endpoint=False)
    angles_inner = angles_outer + np.pi / num_points
    angles = np.empty(num_points * 2)
    angles[0::2] = angles_outer
    angles[1::2] = angles_inner

    radii = np.empty_like(angles)
    for i in range(len(angles)):
        base_r = r_outer if i % 2 == 0 else r_inner
        radii[i] = base_r * (1 + wobble * (random.random() - 0.5))

    x = cx + radii * np.cos(angles)
    y = cy + radii * np.sin(angles)
    x = np.append(x, x[0])
    y = np.append(y, y[0])
    return x, y

# --- Sidebar controls ---
st.sidebar.title("Poster Settings")
palette_mode = st.sidebar.selectbox("Palette Mode", ["vivid", "pastel", "random"])
n_layers = st.sidebar.slider("Number of Stars", 3, 15, 7)
wobble = st.sidebar.slider("Star Wobble", 0.0, 0.3, 0.1)

# --- Generate Palette ---
palette = random_palette(6, mode=palette_mode)

# Display Palette
st.subheader("Generated Palette")
fig_pal, ax_pal = plt.subplots(figsize=(6,1))
ax_pal.axis('off')
for i, c in enumerate(palette):
    rect = plt.Rectangle((i,0), 1, 1, color=c)
    ax_pal.add_patch(rect)
ax_pal.set_xlim(0,len(palette))
ax_pal.set_ylim(0,1)
st.pyplot(fig_pal)

# --- Generate Poster ---
st.subheader("Generative Star Poster")
fig, ax = plt.subplots(figsize=(7,10))
ax.axis('off')
ax.set_facecolor((0.98,0.98,0.97))

for i in range(n_layers):
    cx, cy = random.random(), random.random()
    outer_r = random.uniform(0.15, 0.4)
    inner_r = outer_r * random.uniform(0.35, 0.55)
    x, y = true_star(center=(cx,cy), r_outer=outer_r, r_inner=inner_r, num_points=5, wobble=random.uniform(0.02, wobble))
    color = random.choice(palette)
    alpha = random.uniform(0.3,0.6)
    ax.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# Safe text display to avoid JS error
ax.text(0.05, 0.95, "Generative Star Poster", fontsize=18, weight='bold', transform=ax.transAxes)
ax.text(0.05, 0.91, "Week 2 - Arts & Advanced Big Data", fontsize=11, transform=ax.transAxes)

ax.set_xlim(0,1)
ax.set_ylim(0,1)
st.pyplot(fig)